python3: can't open file 'docs/user_guide_generator/create_complete_guide.py': [Errno 2] No such file or directory
